server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
    ## DİKKAT!!!! gelen istek predicates ile tespit edilerek ilgili service yönlendiriliyor. Peki,
    ## isteğin hangi controller ve action a gideceği nasıl bilinecek?
      routes:
        - id: auth-service
          uri: http://service-loadbalancer-auth:9090
          predicates:
            - Path=/auth/** # http://www.mysite.com/auth/register -> http://service-loadbalancer-auth:9090
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: authFallback
                fallbackUri: forward:/fallback/auth
                statusCodes:
                  - 500
                  - "NOT_FOUND"
        - id: user-service
          uri: http://service-loadbalancer-user:9091
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: userFallback
                fallbackUri: forward:/fallback/user
                statusCodes:
                  - 500
                  - "NOT_FOUND"
      default-filters:
        - RewritePath= /(?<segment>.*) , /dev/v1/$\{segment}
      ##               /auth/register  , /dev/v1/auth/register
      ## registerauth: http://service-loadbalancer-auth:9090/dev/v1/auth/register
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
