apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer-postgersql
spec:
  selector:
    db: db-postgresql
  type: LoadBalancer
  ports:
  - name: postgresqltcp
    port: 55555
    targetPort: 5432