apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer-config
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
  - name: configtcp
    port: 8888
    targetPort: 8888