apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-rabbitmq
spec:
  selector:
    db: db-rabbitmq
  type: ClusterIP
  ports:
  - name: rabbitrest
    port: 5672
    targetPort: 5672
  - name: rabbitgiu
    port: 15672
    targetPort: 15672