server:
  port: 9090

spring:
  datasource:
    url: ${DB_POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bilge*!
  jpa:
    hibernate:
      ddl-auto: update
